---
- name: Ensure custom facts directory exist
  win_file:
      path: 'C:\dwf-ansible\custom_facts'
      state: directory

- name: Copy fact file
  win_copy:
      src: 'fact_ip.ps1'
      dest: 'C:\dwf-ansible\custom_facts\local_users.ps1'

- name: Set ansible local variable
  set_fact:
      key_value:
        fact_path: 'C:\dwf-ansible\custom_facts'

- name: Reload ansible_local
  setup: 
    filter: ansible_local
    fact_path: 'C:\dwf-ansible\custom_facts'
  register: ansible_local

- name: Print out custom fact
  debug:
    msg: "{{ ansible_fact_ip }}"